- id: '1748847589440'
  alias: 'Alarm: Trigger Alarm when Armed Away'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.alarm_motion_sensors
    to: 'on'
  conditions:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  actions:
  - action: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
    data: {}
  mode: single
- id: '1748848067532'
  alias: Alarm_1
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.alarm_motion_sensors
    to: 'on'
  conditions:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  actions: []
  mode: single
- id: '1748849182152'
  alias: Ny automatisering
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.alarm_motion_sensors
    to: 'on'
  conditions: []
  actions: []
  mode: single
