---
# Cellar climate monitoring
#
substitutions:
  label: esp01
  slug: cellar_climate
  name: Cellar climate
  description: Monitor the climate of the celler
  encryption_key: !secret esphome_cellar_climate_encryption_key
  ota_password: !secret esphome_cellar_climate_ota_password

packages:
  <<: !include_dir_named common
  board: !include boards/esp32dev.yaml

status_led:
  pin:
    number: GPIO13
    inverted: true