---
# crawl space monitoring
#
substitutions:
  label: esp01
  slug: crawlspace
  name: crawl space
  description: Monitor the crawl space 
  encryption_key: !secret esphome_crawl_space_encryption_key
  ota_password: !secret esphome_crawl_space_ota_password

packages:
  <<: !include_dir_named common
  board: !include boards/olimex_esp32_devkitlipo.yaml

# Example configuration entry
sensor:
  - platform: dht
    pin: GPIO13
    temperature:
      name: "Krypgrund temperatur"
    humidity:
      name: "Krypgrund luftfuktighet"
    update_interval: 60s